global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

  metrics:
    address: ":8082"

  admin:
    address: ":8090"

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@secureshield.io
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

  kubernetesIngress:
    ingressClass: traefik

  redis:
    endpoints:
      - "secureshield-redis:6379"

log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics

ping:
  entryPoint: web

accessLog:
  filePath: /var/log/traefik/access.log
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep